---
# Synopsis: Ignore rac audit for vaults
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: Azure.Keyvault.RBAC
  description: 'not to have rbac enabled for sandbox sub'
spec:
  rule:
    - Azure.KeyVault.RBAC
  if:
    type: '.'
    in:
      - 'Microsoft.KeyVault/vaults'


---
# Synopsis: Storage Accounts should only accept explicitly allowed traffic.
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: Azure.Keyvault.RBAC
  description: 'not to have rbac enabled for sandbox sub'
spec:
  rule:
    - Azure.Storage.Firewall
  if:
    field: '$.name'
    equals: 'test2334'