---
# Synopsis: Ignore rac audit for vaults
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: Azure.Keyvault.RBAC
  description: 'not to have rbac enabled for sandbox sub'
spec:
  rule:
    - Azure.KeyVault.RBAC
  if:
    type: '.'
    in:
      - 'Microsoft.KeyVault/vaults'