---
# Synopsis: Ignore rac audit for vaults
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: Azure.Keyvault.RBAC
  description: 'not to have rbac enabled for sandbox sub'
spec:
  rule:
    - Azure.KeyVault.RBAC
  if:
    type: '.'
    in:
      - 'Microsoft.KeyVault/vaults'


---
---
# Synopsis: Suppress Azure.Storage.Firewall for 'test2334' storage account when networkAcls.defaultAction is missing.
# Reason for suppression: The field 'properties.networkAcls.defaultAction' does not exist, which is expected for this resource.
apiVersion: github.com/microsoft/PSRule/v1
kind: SuppressionGroup
metadata:
  name: SuppressTest2334StorageFirewallMissingNacl # A unique, descriptive name for this specific suppression
  description: 'Suppress AZR-000202 for storage account "test2334" specifically when its networkAcls.defaultAction property is not defined.'
spec:
  rule:
    - Azure.Storage.Firewall # The exact rule ID from the error
  if:
    allOf:
      # Condition 1: Target the specific resource by name
      - field: '$.Name'
        equals: 'test2334'
      # Condition 2: Ensure it's a Storage Account (good practice for precision)
      - type: '.'
        in:
          - 'Microsoft.Storage/storageAccounts'
      # Condition 3: Suppress ONLY if the 'properties.networkAcls.defaultAction' field does NOT exist
      # This matches the exact "Reason" given in your error output.
      - field: properties.networkAcls.defaultAction
        exists: false # <--- THIS IS THE CRUCIAL CHANGE
  # Optional: Add an expiration date if this suppression is temporary
  # expires: 2026-06-26T23:59:59Z # Example: expires in one year from today (June 26, 2025)